pub const NPROC = 64; // maximum number of processes
pub const NCPU = 8; // maximum number of CPUs
pub const NOFILE = 16; // open files per process
pub const NFILE = 100; // open files per system
pub const NINODE = 50; // maximum number of active i-nodes
pub const ROOTDEV = 1; // device number of file system root disk
pub const MAXARG = 32; // max exec arguments
pub const max_num_operation_blocks = 10; // max # of blocks any FS op writes
pub const log_size = (max_num_operation_blocks * 3); // max data blocks in on-disk log
pub const NBUF = (max_num_operation_blocks * 3); // size of disk block cache
pub const FSSIZE = 2000; // size of file system in blocks
pub const MAXPATH = 128; // maximum file path name
pub const kernel_stack_page_count = 6; // pages used for kernel stack
